vich_uploader:
    db_driver: orm

    mappings:
        bien_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            # directory_namer:
            #       service: vich_uploader.namer_directory_current_date_time
            #       options:
            #           date_time_format: 'Y.m.d.H.i.s'            
            namer:
                 service: Vich\UploaderBundle\Naming\UniqidNamer